name: Run Test
on: [pull_request]

jobs:
  run_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install Bun ${{ matrix.node-version }}
        run: npm install -g bun

      - name: Check Dependency Cache
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: ${{runner.os}}-node-${{hashFiles('./bun.lockb')}}

      - name: Install Bun and Dependencies
        run:
          bun install

      - name: Run Tests
        run: bun run test

      - name: Install Cypress
        run:
          bun cypress install

      - name: Run Cypress
        run:
          bun run cypress-test
          